# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: home
  joint_model_group_pose: gripper
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
    - gripper_finger1_joint
  sim_control_mode: 1  # 0: position, 1: velocity

# # 真机上用的
# controller_list:
#   - name: "scaled_pos_joint_traj_controller"
#     action_ns: follow_joint_trajectory
#     type: FollowJointTrajectory
#     default: True
#     joints:
#       - shoulder_pan_joint
#       - shoulder_lift_joint
#       - elbow_joint
#       - wrist_1_joint
#       - wrist_2_joint
#       - wrist_3_joint

#   - name: ag95_controller
#     action_ns: follow_joint_trajectory
#     # type: position_controllers/JointTrajectoryController
#     type: position_controllers/ScaledPosJointTrajectoryController
#     default: True
#     joints:
#       - gripper_finger1_joint

# 仿真用
ur3_controller:
    # action_ns: follow_joint_trajectory
    # type: FollowJointTrajectory
    type: position_controllers/JointTrajectoryController
    default: True
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

ag95_controller:
    # action_ns: follow_joint_trajectory
    # type: FollowJointTrajectory
    type: position_controllers/JointTrajectoryController
    default: True
    joints:
      - gripper_finger1_joint

# - name: "scaled_pos_joint_traj_controller"
#   action_ns: follow_joint_trajectory
#   type: FollowJointTrajectory

# controller_list:
#   # - name: ur3_controller
#     action_ns: follow_joint_trajectory
#     type: FollowJointTrajectory
#     # type: position_controllers/JointTrajectoryController
#     default: True
#     joints:
#       - shoulder_pan_joint
#       - shoulder_lift_joint
#       - elbow_joint
#       - wrist_1_joint
#       - wrist_2_joint
#       - wrist_3_joint
#       - gripper_finger1_joint

  # - name: ag95_controller
  #   action_ns: follow_joint_trajectory
  #   type: FollowJointTrajectory
  #   default: True
  #   joints:
  #     - gripper_finger1_joint
# controller_list:
